[WALL-14933]: Update SDK to support multiple wallets
MobileWalletProtocol/wallet-mobile-sdk pull request #117
Opened 2022-11-07 03:17 UTC by AMITGOELNY

### _Summary_

* Modify `CoinbaseWalletSDK` to now support multiple instances, instead of previously accessible singleton object.
* For response handling, parse host url from message's callback property to retrieve `CoinbaseWalletSDK` instance
* Updated example apps to support multiple wallets

### _How did you test your changes?_

https://user-images.githubusercontent.com/4512097/200218895-bd246a46-31b3-40fc-acc2-69bdf33138f2.mov

2022-11-07 15:11 UTC, bangtoven commented on Provider/WalletProvider.swift
> +//
this file needs to be somewhere under `ios/CoinbaseWalletSDK` path

2022-11-07 15:22 UTC, bangtoven requested changes

2022-11-07 15:22 UTC, bangtoven commented on Provider/WalletProvider.swift
> +    }
doesn't seem valid

2022-11-07 15:22 UTC, bangtoven commented on Provider/WalletProvider.swift
> +                                 iconUrl: "https://play-lh.googleusercontent.com/wrgUujbq5kbn4Wd4tzyhQnxOXkjiGqq39N4zBvCHmxpIiKcZw_Pb065KTWWlnoejsg",
let's use coinbase url that we control, or at least app store ones.

2022-11-07 15:22 UTC, bangtoven commented on ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
> +    static public func getInstance(hostWallet: Wallet, callback: URL) -> CoinbaseWalletSDK {
seems we need to keep `configure` to define `callback`. 
these params don't seem related to each other

2022-11-07 15:22 UTC, bangtoven commented on ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
> +        guard let instance = instances[URL(string: encryptedResponse.callbackUrl ?? "")!] else {
why not checking this after `isWalletSegueMessage`?
also, it would make more sense to throw an error for this case, instead of returning just boolean

2022-11-07 15:22 UTC, bangtoven commented on ios/example/SampleClient/ViewController.swift
> +            let actions = await walletProvider.getWallets().map { wallet in
can we load `walletProvider.getWallets()` once during viewDidLoad, and make these calls synchronous?

2022-11-07 15:23 UTC, cb-heimdall commented
Review Error for bangtoven @ 2022-11-07 15:23:32 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

2022-11-07 17:42 UTC, AMITGOELNY commented on Provider/WalletProvider.swift
> +    }
what should we put here? not an easy for iOS to auto gen app store links for ios

2022-11-07 19:23 UTC, vishnumad commented on Provider/WalletProvider.swift
> +                                       packageName: "",
Why's package name empty? Is this supposed to be the app's bundle/app id?

2022-11-07 19:23 UTC, vishnumad commented on Provider/WalletProvider.swift
> +public protocol CoinbaseWalletProviderProtocol {
CoinbaseWalletProvider -> MobileWalletProvider maybe

2022-11-07 19:23 UTC, vishnumad commented on Provider/WalletProvider.swift
> +    public static let coinbase = Wallet(name: "Coinbase Wallet",
coinbase -> coinbaseWallet

2022-11-07 19:23 UTC, vishnumad commented on Provider/WalletProvider.swift
> +    }
This would return the CBW app store url for all Wallets. Can this be a parameter that's passed in via constructor?

2022-11-07 19:23 UTC, vishnumad commented on ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
> +    static public func getInstance(hostWallet: Wallet, callback: URL) -> CoinbaseWalletSDK {
+1, needing to pass in callback url every time an sdk instance is retrieved seems a bit cumbersome.

2022-11-07 20:59 UTC, AMITGOELNY commented on Provider/WalletProvider.swift
> +                                       packageName: "",
for android, it's of use, on iOS, not sure where bundleId would be used.

2022-11-07 22:57 UTC, AMITGOELNY commented on Provider/WalletProvider.swift
> +//
moved to ios/CoinbaseWalletSDK path

2022-11-07 22:57 UTC, AMITGOELNY commented on Provider/WalletProvider.swift
> +    }
updated to be passed in as a param

2022-11-07 22:58 UTC, AMITGOELNY commented on Provider/WalletProvider.swift
> +                                 iconUrl: "https://play-lh.googleusercontent.com/wrgUujbq5kbn4Wd4tzyhQnxOXkjiGqq39N4zBvCHmxpIiKcZw_Pb065KTWWlnoejsg",
updated with app store icon links

2022-11-07 22:58 UTC, AMITGOELNY commented on ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
> +    static public func getInstance(hostWallet: Wallet, callback: URL) -> CoinbaseWalletSDK {
kept configure static method

2022-11-07 22:58 UTC, AMITGOELNY commented on ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
> +        guard let instance = instances[URL(string: encryptedResponse.callbackUrl ?? "")!] else {
updated to move isWalletSegueMessage prior to instance retrieval

2022-11-07 22:59 UTC, AMITGOELNY commented on ios/example/SampleClient/ViewController.swift
> +            let actions = await walletProvider.getWallets().map { wallet in
updated

2022-11-07 22:59 UTC, AMITGOELNY commented on Provider/WalletProvider.swift
> +public protocol CoinbaseWalletProviderProtocol {
name updated

2022-11-07 22:59 UTC, AMITGOELNY commented on Provider/WalletProvider.swift
> +    public static let coinbase = Wallet(name: "Coinbase Wallet",
updated name

2022-11-08 08:25 UTC, bangtoven commented on Provider/WalletProvider.swift
> +public struct DefaultWallet {
```suggestion
extension Wallet {
```

2022-11-08 08:25 UTC, bangtoven commented on Provider/WalletProvider.swift
> +        return [DefaultWallet.coinbase, DefaultWallet.coinbaseRetail]
```suggestion
        return [.coinbase, .coinbaseRetail]
```

2022-11-08 08:25 UTC, bangtoven commented on Provider/WalletProvider.swift
> +                                       packageName: "",
+1. remove it if it's unnecessary.

2022-11-08 08:26 UTC, bangtoven commented on ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
> +                callback: CoinbaseWalletSDK.callback!,
avoid using force unwrapping. 
this should be defined before initiating the instance.

2022-11-08 08:27 UTC, bangtoven commented on ios/example/SampleClient/ViewController.swift
> +        sdkClient?.makeRequest(
```suggestion
        guard let sdkClient = CoinbaseWalletSDK.getInstance(hostWallet: wallet) else {...}
        sdkClient.makeRequest(
```

2022-11-08 08:29 UTC, bangtoven commented on ios/CoinbaseWalletSDK/Provider/MobileWalletProvider.swift
> +                                              packageName: "",
as @vishnumad 's point, i'd just remove this if it's not necessary

2022-11-08 08:29 UTC, bangtoven commented on ios/CoinbaseWalletSDK/Provider/MobileWalletProvider.swift
> +public struct DefaultWallet {
```suggestion
extension Wallet {
```

2022-11-08 08:29 UTC, bangtoven commented on ios/CoinbaseWalletSDK/Provider/MobileWalletProvider.swift
> +        return [DefaultWallet.coinbaseWallet, DefaultWallet.coinbaseRetail]
```suggestion
        return [.coinbaseWallet,.coinbaseRetail]
```

2022-11-08 16:23 UTC, AMITGOELNY commented
PR updated based on comments.

2022-11-08 17:37 UTC, AMITGOELNY commented
@bangtoven any idea why these tests are failing?

2022-11-14 18:44 UTC, bangtoven commented
> @bangtoven any idea why these tests are failing?

it's bc of `async` thing being used. our sdk doesn't have support for swift concurrency.
![image](https://user-images.githubusercontent.com/966662/201740244-65e03dbc-f6db-408a-8c4c-61b263de97ee.png)

we might just make it a regular function
@AMITGOELNY

2022-11-14 20:13 UTC, bangtoven commented on ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
> +        guard let instance = instances[URL(string: encryptedResponse.callbackUrl ?? "")!] else {
`callback` thing would be empty with older version of host

2022-11-14 21:25 UTC, AMITGOELNY commented
> > @bangtoven any idea why these tests are failing?
> 
> it's bc of `async` thing being used. our sdk doesn't have support for swift concurrency. ![image](https://user-images.githubusercontent.com/966662/201740244-65e03dbc-f6db-408a-8c4c-61b263de97ee.png)
> 
> we might just make it a regular function @AMITGOELNY

updated

2022-11-14 22:52 UTC, bangtoven commented on ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
> +    private static var callback: URL?
nit: let's keep line 22 instead 
![image](https://user-images.githubusercontent.com/966662/201784738-c7a5b5e9-3882-48c8-8fdc-2d6f35fc4a66.png)

2022-11-14 22:56 UTC, bangtoven commented on ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
> +        guard let instance = instances[URL(string: encryptedResponse.callbackUrl ?? "")!] else {
i know you planned to merge this one first, but i believe we should address the `handleResponse` changes as we discussed on this pr to have correct/sound support for multi wallets. 
let's use existing `requestId` instead of the new `callbackUrl` 
![image](https://user-images.githubusercontent.com/966662/201785247-84da1dab-adad-48e4-b270-ce8a4b6bf1fb.png)

2022-11-14 23:42 UTC, AMITGOELNY commented on ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
> +        guard let instance = instances[URL(string: encryptedResponse.callbackUrl ?? "")!] else {
updated to use RequestId

2022-11-15 19:43 UTC, bangtoven reviewed
@AMITGOELNY

2022-11-15 19:43 UTC, bangtoven commented on ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
> +    static public func configure(callback: URL) {
i believe we should keep `isConfigured` for RN cc @vishnumad 

```suggestion
    static private var callback: URL?
    static public var isConfigured: Bool {
        return .... // 
    }

    static public func configure(callback: URL) {
```

2022-11-15 19:43 UTC, bangtoven commented on ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
> +    static private var callback: URL?
```suggestion
    private let callback: URL
```

i think we should keep this to make sure that every instance has concrete callback URL, instead of checking static value on instance methods like below.
![image](https://user-images.githubusercontent.com/966662/202007038-4e906677-f487-4101-be4a-602300473601.png)

2022-11-15 19:43 UTC, bangtoven commented on ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
> +    private static var instances: [URL: CoinbaseWalletSDK] = [:]// host url -> instance
```suggestion
    private static var instances: [URL: CoinbaseWalletSDK] = [:]// host url -> instance
    
```

2022-11-15 19:43 UTC, bangtoven commented on ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
> +        CoinbaseWalletSDK.instances[host] = self
this seems kinda dependency inversion, also it's redundant. i think it would be better to avoid having this kinda logic on constructor. on line 36, the static function already does `instances[host] = newInstance` btw.

2022-11-15 19:43 UTC, bangtoven commented on ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
> +            callbackUrl: CoinbaseWalletSDK.callback!.absoluteString
see comment on line 47. we should avoid force unwrapping

2022-11-15 19:43 UTC, bangtoven commented on ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
> +
see comment on line 47

2022-11-15 19:43 UTC, bangtoven commented on ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
> +            callbackUrl: CoinbaseWalletSDK.callback!.absoluteString
same

2022-11-15 19:43 UTC, bangtoven commented on ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
> +            TaskManager.registerResponseHandler(for: request, host: self.host, onResponse)
👍

2022-11-15 19:43 UTC, bangtoven commented on ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
> +        return url.host == CoinbaseWalletSDK.callback!.host && url.path == CoinbaseWalletSDK.callback!.path
avoid force unwrapping

2022-11-15 19:43 UTC, bangtoven commented on ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
> +        guard let instance = instances[request!] else {
avoid force unwrapping
```suggestion
        guard 
            let request = TaskManager.getHost(for: encryptedResponse),
            let instance = instances[request!] else {
```

2022-11-15 19:43 UTC, bangtoven commented on ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
> +    private func decodeResponse(_ url: URL,_ encryptedResponse: EncryptedResponseMessage) throws -> ResponseMessage {
let's use either one of them
```suggestion
    private func decodeResponse(_ EncryptedResponseMessage) throws -> ResponseMessage {
```

2022-11-15 19:43 UTC, bangtoven commented on ios/CoinbaseWalletSDK/Provider/MobileWalletProvider.swift
> +                                              appStoreUrl: "https://apps.apple.com/us/app/coinbase-wallet-nfts-crypto/id1278383455")
this should use universal link
+ nit: swift convention

```suggestion
    public static let coinbaseWallet = Wallet(
        name: "Coinbase Wallet",
        iconUrl: "https://is1-ssl.mzstatic.com/image/thumb/Purple122/v4/bd/2b/dc/bd2bdcac-44ff-0707-3ec1-fde5014a91a1/AppIcon-0-0-1x_U007emarketing-0-0-0-10-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/100x100bb.jpg",
        url: "https://........",
        appStoreUrl: "https://apps.apple.com/us/app/coinbase-wallet-nfts-crypto/id1278383455"
)
```

2022-11-15 19:43 UTC, bangtoven commented on ios/CoinbaseWalletSDK/Task/TaskManager.swift
> +    static func findRequest(for response: EncryptedResponseMessage) -> RequestMessage? {
how about
```suggestion
    static func findRequest(for requestId: UUID) -> RequestMessage? {
```
i think this will be more flexible

2022-11-15 19:43 UTC, bangtoven commented on ios/CoinbaseWalletSDK/Test/ExampleTest.swift
> +        XCTAssertFalse(client?.isConnected() ?? false)
i don't understand what this test is about

2022-11-15 19:43 UTC, bangtoven commented on ios/example/SampleClient/AppDelegate.swift
> +        CoinbaseWalletSDK.configure(callback: URL(string: "myappxyz://mycallback")!)
is there a reason to drop the warning message?

2022-11-15 19:43 UTC, bangtoven commented on ios/example/SampleClient/AppDelegate.swift
> +        if (try? CoinbaseWalletSDK.handleResponse(url)) == true {
👍

2022-11-15 19:54 UTC, vishnumad commented on ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
> +    static public func configure(callback: URL) {
Yes, let's keep `isConfigured`. The expo module is currently not using it, but it should use this instead of keeping its own hasConfigured variable. https://github.com/coinbase/wallet-mobile-sdk/blob/master/react-native/ios/CoinbaseWalletSDKModule.swift#L40

2022-11-15 23:51 UTC, bangtoven commented on ios/example/SampleClient/ViewController.swift
> +    private var wallets: [Wallet] = []
let's just get coinbaseWallet instance like below, and revert other changes.
```suggestion
    private lazy var cbwallet = { CoinbaseWalletSDK.getInstance(hostWallet: .coinbaseWallet) }()
```

2022-11-16 23:29 UTC, AMITGOELNY commented on ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
> +    static public func configure(callback: URL) {
Added `isConfigured` back in.

2022-11-16 23:29 UTC, AMITGOELNY commented on ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
> +    private func decodeResponse(_ url: URL,_ encryptedResponse: EncryptedResponseMessage) throws -> ResponseMessage {
for this, not sure what we can do, as I need the url to get the symmetricKey

2022-11-16 23:29 UTC, AMITGOELNY commented on ios/example/SampleClient/AppDelegate.swift
> +        CoinbaseWalletSDK.configure(callback: URL(string: "myappxyz://mycallback")!)
Added the warning message back

2022-11-16 23:43 UTC, bangtoven commented on ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
> +    private let callbackURL: URL
nit: any reasons in renaming this? if we are going to, let's update `host` as `hostURL` as well for consistency, or keep it as it is.

2022-11-16 23:43 UTC, bangtoven commented on ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
> +    private func decodeResponse(_ url: URL,_ encryptedResponse: EncryptedResponseMessage) throws -> ResponseMessage {
then let's refactor `MessageConverter.decode` to take `EncryptedContent` instead. we can address it on follow up

2022-11-16 23:43 UTC, bangtoven commented on ios/CoinbaseWalletSDK/Provider/MobileWalletProvider.swift
> +public class MobileWalletProvider : MobileWalletProviderProtocol {
what is this protocol for? can it be just
```suggestion
public class MobileWalletProvider {
```

2022-11-16 23:43 UTC, bangtoven commented on ios/CoinbaseWalletSDK/Provider/MobileWalletProvider.swift
> +
```suggestion
```

2022-11-16 23:43 UTC, bangtoven commented on ios/CoinbaseWalletSDK/Provider/MobileWalletProvider.swift
> +    public func getWallets() -> [Wallet] {
seems it would better to be a static method

2022-11-16 23:43 UTC, bangtoven commented on ios/CoinbaseWalletSDK/Provider/MobileWalletProvider.swift
> +    }
why do we need this and `MobileWalletProvider` also?

2022-11-16 23:43 UTC, bangtoven commented on ios/CoinbaseWalletSDK/Task/TaskManager.swift
> +        }
we can do something like
```suggestion
        tasks.removesAll(where: { $.value.host == host })
```

2022-11-16 23:43 UTC, bangtoven commented on ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
> +        guard let request = TaskManager.getHost(for: encryptedResponse),
seems something is wrong
`getHost` returning `request`

2022-11-16 23:43 UTC, bangtoven commented on ios/CoinbaseWalletSDK/Test/ExampleTest.swift
> +        CoinbaseWalletSDK.configure(callback: URL(string: "https://test.com")!)
let's keep it as master if there's no change

2022-11-16 23:43 UTC, bangtoven commented on ios/CoinbaseWalletSDK/Task/TaskManager.swift
> +    }
1. let's give them consistent name, `getRequest` `getHost` OR `findRequest` `findHost`
2. actually, i think we might just consolidate this as `findTask(for requestId)` and let callers decide which properties to use

2022-11-16 23:47 UTC, bangtoven commented on ios/CoinbaseWalletSDK/Provider/MobileWalletProvider.swift
> +
these should be immutable
```suggestion
    public let name: String
    public let iconUrl: String
    public let url: String
    public let appStoreUrl: String
    
```

2022-11-16 23:47 UTC, bangtoven commented on ios/CoinbaseWalletSDK/Provider/MobileWalletProvider.swift
> +//  WalletProvider.swift
i would just rename this `./Wallet.swift` or something and drop `MobileWalletProvider` class as `Wallet.defaultValues` exists

2022-11-16 23:53 UTC, AMITGOELNY commented on ios/CoinbaseWalletSDK/Task/TaskManager.swift
> +        }
this doesn't appear to compile

2022-11-16 23:53 UTC, bangtoven commented on ios/CoinbaseWalletSDK/Provider/MobileWalletProvider.swift
> +public class MobileWalletProvider : MobileWalletProviderProtocol {
actually, let's just remove this class and use `Wallet.defaultValues`

2022-11-16 23:56 UTC, bangtoven commented on ios/CoinbaseWalletSDK/Provider/MobileWalletProvider.swift
> +    static public func defaultValues() -> [Wallet] {
```suggestion
    static public func defaultWallets() -> [Wallet] {
```

2022-11-16 23:57 UTC, bangtoven commented on ios/CoinbaseWalletSDK/Task/TaskManager.swift
> +        }
@AMITGOELNY 
tasks.removesAll(where: { $0.value.host == host })
https://developer.apple.com/documentation/swift/array/removeall(where:)-5k61r

2022-11-17 00:07 UTC, bangtoven reviewed
@AMITGOELNY

2022-11-17 00:07 UTC, bangtoven commented on ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
> +    private init(_ host: URL,_ callback: URL) {
these params both have URL types. let's keep tags
```suggestion
    private init(host: URL, callback: URL) {
```

2022-11-17 00:07 UTC, bangtoven commented on ios/CoinbaseWalletSDK/Task/TaskManager.swift
> +        }
i think you can figure out how to make it compile

2022-11-17 00:11 UTC, bangtoven commented on ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
> +    private let callbackURL: URL
if we are gonna name them **URL, let's have them consistent across the library. 
otherwise, keep them as they were and drop ***URL everywhere
![image](https://user-images.githubusercontent.com/966662/202322279-614fe528-e8ff-4498-b33d-67138641058d.png)

2022-11-17 00:21 UTC, bangtoven approved these changes

2022-11-17 00:25 UTC, merged

2023-12-17 05:42 UTC, KK68HK commented on ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
> +        guard let instance = instances[URL(string: encryptedResponse.callbackUrl ?? "")!] else {
Jag förstår inte nå varför allt ska va så krångligt

2023-12-17 05:43 UTC, KK68HK commented on ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
> +        guard let instance = instances[URL(string: encryptedResponse.callbackUrl ?? "")!] else {
> Jag förstår inte nå varför allt ska va så krångligt