diagnosticLog
MobileWalletProtocol/wallet-mobile-sdk pull request #134
Opened 2022-11-21 23:42 UTC by bangtoven

### _Summary_

### _How did you test your changes?_

2022-11-21 23:45 UTC, bangtoven commented on react-native/host/src/events/events.ts
> +export function diagnosticLog(event: MWPEvent) {
https://github.com/coinbase/coinbase-wallet-sdk/pull/521
maybe i am too anxious or overcautious about this, but iirc, we had similar discussion on how we'd call the logger object in the web sdk side and avoid any confusion from users. 
curious how you think @vishnumad

2022-11-21 23:49 UTC, vishnumad commented on react-native/host/src/events/events.ts
> +export function diagnosticLog(event: MWPEvent) {
Gotcha, sounds good. Maybe the function `addEventListener` should be renamed to `addDiagnosticListener` or something similar.

2022-11-21 23:49 UTC, vishnumad approved these changes, later dismissed

2022-11-21 23:53 UTC, bangtoven commented on react-native/host/src/events/events.ts
> +export function diagnosticLog(event: MWPEvent) {
great. made the suggested changes as well

2022-11-22 00:00 UTC, vishnumad requested changes

2022-11-22 00:00 UTC, vishnumad commented on react-native/client/example/App.js
> +    const subscription = Linking.addDiagnosticLogListener('url', ({url}) => {
This one shouldn't be changed since it's for incoming deeplinks

2022-11-22 00:01 UTC, cb-heimdall commented
Review Error for vishnumad @ 2022-11-22 00:01:35 UTC
User failed mfa authentication, public email is not set on your github profile. see [go/mfa-help](http://go/mfa-help)

2022-11-22 00:12 UTC, bangtoven commented on react-native/client/example/App.js
> +    const subscription = Linking.addDiagnosticLogListener('url', ({url}) => {
duh... fixed it

2022-11-22 00:24 UTC, vishnumad approved these changes

2022-11-22 00:24 UTC, merged